name: 'Deploy with vkube-cli'
description: 'Deploy containers using vkube-cli with Docker Hub/GHCR login and version checks'
author: 'certram'

inputs:
  vkube_config_file:
    description: 'Path to VKubefile.yaml'
    required: true
    default: './VKubefile.yaml'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Check tools
      shell: bash
      run: |
        python --version
        pip --version
        docker --version

    - name: Install and verify vkube-cli
      shell: bash
      run: |
        pip install vkube==1.0.4
        vkube version

    - name: Parse registry from VKubefile
      shell: bash
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        # 安装 yq
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

        # 解析 registry
        REGISTRY=$(yq '.imageRegistry' "${{ inputs.vkube_config_file }}")
        echo "Found registry: $REGISTRY"

        # 设置环境变量
        case "$REGISTRY" in
          "ghcr")
            echo "registry=ghcr.io" >> $GITHUB_ENV
            echo "registry_username=$GITHUB_ACTOR" >> $GITHUB_ENV
            echo "registry_password=$GHCR_TOKEN" >> $GITHUB_ENV
            ;;
          "docker")
            echo "registry=docker.io" >> $GITHUB_ENV
            echo "registry_username=$DOCKERHUB_USERNAME" >> $GITHUB_ENV
            echo "registry_password=$DOCKERHUB_TOKEN" >> $GITHUB_ENV
            ;;
          *)
            echo "Unsupported registry: $REGISTRY"
            exit 1
            ;;
        esac

    - name: Login to container registry
      if: env.registry != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ env.registry_username }}
        password: ${{ env.registry_password }}

    - name: Run vkube deploy
      shell: bash
      run: |
        vkube deploy -f "${{ inputs.vkube_config_file }}"